name: Test Windows

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ '**.cpp', '**.hpp*', '**.cmake', 'include/yaclib_std/*', '**/CMakeLists.txt' ]
  pull_request:
    branches: [ main ]
    paths: [ '**.cpp', '**.hpp*', '**.cmake', 'include/yaclib_std/*', '**/CMakeLists.txt' ]

jobs:
  msvc:
    if: >-
      !contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      !contains(toJSON(github.event.commits.*.message), '[skip github]')

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    
    strategy:
      fail-fast: false
      matrix:
        arch: [ Win32, x64 ]
        os: [ windows-2022, windows-2025 ]
        build_type: [ Debug, RelWithDebInfo ]

        exclude:
          - os: windows-2025
            is_pr: ${{ github.event_name == 'pull_request' }}

    env:
      BUILD_DIR: build/

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          arch=${{ matrix.arch }}
          if [[ "$arch" == "Win32" ]]; then
            slowdown=5
          elif [[ "$arch" == "x64" ]]; then
            slowdown=1
          fi

          os=${{ matrix.os }}
          if [[ "os" == "windows-2022" ]]; then
            generator="Visual Studio 17 2022"
          elif  [[ "os" == "windows-2025" ]]; then
            generator="Visual Studio 18 2026"
          fi

          # TODO(shpana): Maybe use CMakePresets.txt
          cmake -S . -B $BUILD_DIR                                                                                     \
              -DYACLIB_CXX_STANDARD=17                                                                                 \
              -DYACLIB_TEST=SINGLE                                                                                     \
              -DYACLIB_LOG="DEBUG"                                                                                     \
              -DYACLIB_FLAGS="CORO"                                                                                    \
              -DYACLIB_DEFINITIONS="YACLIB_CI_SLOWDOWN=$slowdown"                                                      \
              -G "$generator"                                                                                          \
              -A $arch

      - name: Build
        run: |
          cmake --build $BUILD_DIR --config ${{ matrix.build_type }} --parallel
      
      - name: Test
        run: |
          cd $BUILD_DIR 
          ctest --output-on-failure -C ${{ matrix.build_type }} -V
          cd ..

  clang-cl:
    if: >-
      !contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      !contains(toJSON(github.event.commits.*.message), '[skip github]')

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    
    strategy:
      fail-fast: false
      matrix:
        arch: [ Win32, x64 ]
        os: [ windows-2022, windows-2025 ]
        build_type: [ Debug, RelWithDebInfo ]
        
        exclude:
          - os: windows-2025
            is_pr: ${{ github.event_name == 'pull_request' }}

    env:
      BUILD_DIR: build/

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: |
          arch=${{ matrix.arch }}
          if [[ "$arch" == "Win32" ]]; then
            slowdown=5
          elif [[ "$arch" == "x64" ]]; then
            slowdown=1
          fi

          os=${{ matrix.os }}
          if [[ "os" == "windows-2022" ]]; then
            generator="Visual Studio 17 2022"
          elif  [[ "os" == "windows-2025" ]]; then
            generator="Visual Studio 18 2026"
          fi

          # TODO(shpana): Maybe use CMakePresets.txt
          # TODO(shpana): Why do not run with CORO flags?
          cmake -S . -B $BUILD_DIR                                                                                     \
              -DYACLIB_CXX_STANDARD=17                                                                                 \
              -DYACLIB_TEST=SINGLE                                                                                     \
              -DYACLIB_LOG="DEBUG"                                                                                     \
              -DYACLIB_DEFINITIONS="YACLIB_CI_SLOWDOWN=$slowdown"                                                      \
              -G "$generator"                                                                                          \
              -A $arch                                                                                                 \
              -T ClangCL 

      - name: Build
        run: |
          cmake --build $BUILD_DIR --config ${{ matrix.build_type }} --parallel
      
      - name: Test
        run: |
          cd $BUILD_DIR 
          ctest --output-on-failure -C ${{ matrix.build_type }} -V
          cd ..

  mingw:
    if: >-
      !contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      !contains(toJSON(github.event.commits.*.message), '[skip github]')

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: msys2 {0}
    
    strategy:
      fail-fast: false
      matrix:
        arch: [ Win32, x64 ]
        os: [ windows-2022, windows-2025 ]
        build_type: [ Debug, RelWithDebInfo ]

        exclude:
          - os: windows-2025
            is_pr: ${{ github.event_name == 'pull_request' }}

    env:
      BUILD_DIR: build/

    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        if: ${{ matrix.arch == 'Win32' }}
        with:
          msystem: mingw32
          install: mingw-w64-i686-cmake mingw-w64-i686-ninja mingw-w64-i686-gcc

      - uses: msys2/setup-msys2@v2
        if: ${{ matrix.arch == 'x64' }}
        with:
          msystem: mingw64
          install: mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja mingw-w64-x86_64-gcc
      
      - name: Configure CMake
        run: |
          arch=${{ matrix.arch }}
          if [[ "$arch" == "Win32" ]]; then
            slowdown=5
          elif [[ "$arch" == "x64" ]]; then
            slowdown=1
          fi

          generator="Ninja"

          # TODO(shpana): Maybe use CMakePresets.txt
          # TODO(shpana): Why do not run with CORO flags?
          cmake -S . -B $BUILD_DIR                                                                                     \
              -DYACLIB_CXX_STANDARD=17                                                                                 \
              -DYACLIB_TEST=SINGLE                                                                                     \
              -DYACLIB_LOG="DEBUG"                                                                                     \
              -DYACLIB_DEFINITIONS="YACLIB_CI_SLOWDOWN=$slowdown"                                                      \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}                                                              \
              -G "$generator"

      - name: Build
        run: |
          cmake --build $BUILD_DIR --config ${{ matrix.build_type }} --parallel
      
      - name: Test
        run: |
          cd $BUILD_DIR 
          ctest --output-on-failure -C ${{ matrix.build_type }} -V
          cd ..
